name: poi

on:
  push:
    branches: master    
    paths:
      - 'apis/poi/**'
  pull_request:
    branches: master 
    paths:
      - 'apis/poi/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
        
    - name: Restore dependencies
      run: dotnet restore poi.sln
      working-directory: apis/poi/
      
    - name: Build
      run: dotnet build --no-restore poi.sln
      working-directory: apis/poi/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: apis/poi/tests/UnitTests

    - name: Login to acr
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push image
      run: |
        docker build -f apis/poi/web/Dockerfile -t ${{secrets.ACR_LOGIN_SERVER}}/devopsoh/api-poi:$GITHUB_RUN_NUMBER apis/poi/web
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:$GITHUB_RUN_NUMBER
            
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Start staging slot
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp start -g openhackqsn13oi5rg -n openhackqsn13oi5poi --slot staging

    - name: Deploy to staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: openhackqsn13oi5poi
        slot-name: staging
        images: '${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${{ github.run_number }}'    
    
    - name: Validate staging is operational
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://openhackqsn13oi5poi-staging.azurewebsites.net/api/healthcheck/poi
        max-attempts: 3 
        retry-delay: 5s 
    
    - name: Swap staging with production
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp deployment slot swap  -g openhackqsn13oi5rg -n openhackqsn13oi5poi --slot staging --target-slot production
    
    - name: Validate production is operational
      uses: jtalk/url-health-check-action@v1.5
      with:
        url: https://openhackqsn13oi5poi.azurewebsites.net/api/healthcheck/poi
        max-attempts: 3 
        retry-delay: 5s 
    
    - name: Stop staging slot
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp stop -g openhackqsn13oi5rg -n openhackqsn13oi5poi --slot staging      
          
    - name: Logout via Azure CLI
      run: |
        az logout
