name: poi

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
        
    - name: Restore dependencies
      run: dotnet restore poi.sln
      working-directory: apis/poi/
      
    - name: Build
      run: dotnet build --no-restore poi.sln
      working-directory: apis/poi/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: apis/poi/tests/UnitTests

    - name: Login to acr
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push image
      run: |
        docker build -f apis/poi/web/Dockerfile -t ${{secrets.ACR_LOGIN_SERVER}}/devopsoh/api-poi:$GITHUB_RUN_NUMBER apis/poi/web
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:$GITHUB_RUN_NUMBER
            
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: openhackqsn13oi5poi
        images: '${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-poi:${GITHUB_RUN_NUMBER}'
    
    - name: Azure logout
      run: |
        az logout
